backend:
  - changed-files:
    - any-glob-to-any-file: "src/main/java/**"
docs:
  - changed-files:
    - any-glob-to-any-file: "docs/**"
infra:
  - changed-files:
    - any-glob-to-any-file: ".github/**"
