backend:
  - changed-files:
      - any-glob-to-any-file: ["src/main/java/**"]

frontend:
  - changed-files:
      - any-glob-to-any-file: ["src/main/frontend/**"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["docs/**"]

infra:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]
